services:
  #  setup:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  volumes:
  #    - /srv:/srv
  #  restart: "no"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.1.0
    container_name: sabnzbd
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mediaserver/sabnzbd/config:/config
    ports:
      - "8080:8080"
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    privileged: true
    volumes:
      - /mediaserver/jellyfin/config:/config
      - /mediaserver/jellyfin/cache:/cache
      - /mnt/z/jellyfin:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
#    runtime: nvidia
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    volumes:
      - /mediaserver/jellyseerr/config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - /mediaserver/radarr/config:/config
      - /mnt/z/jellyfin/Movies:/data
      - /mediaserver/sabnzbd/config/Downloads:/config/Downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - /mediaserver/sonarr/config:/config
      - /mnt/z/jellyfin/Shows:/data
      - /mediaserver/sabnzbd/config/Downloads:/config/Downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - /mediaserver/lidarr/config:/config
      - /mnt/z/jellyfin/Music:/data
      - /mediaserver/sabnzbd/config/Downloads:/config/Downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mediaserver/readarr/config:/config
      - /mnt/z/jellyfin/Books:/data #optional
      - /mediaserver/sabnzbd/config/Downloads:/config/Downloads
    ports:
      - "8787:8787"
    restart: unless-stopped

